import type { CalendarBlock } from "@/lib/planner/data";

export const LANDING_PREVIEW_CREDIT_HOURS = 10;

const COLOR_MATH = "#C4733F";
const COLOR_ENGL = "#6A7C56";
const COLOR_COSC = "#B8893A";

function block(
  partial: Pick<
    CalendarBlock,
    "key" | "dayIndex" | "startMinutes" | "endMinutes" | "label" | "color"
  > &
    Partial<CalendarBlock>,
): CalendarBlock {
  return {
    plannerItemId: partial.plannerItemId ?? 0,
    sectionCrn: partial.sectionCrn ?? "0000",
    meetingId: partial.meetingId ?? 0,
    sublabel: partial.sublabel ?? "",
    instructorSublabel: partial.instructorSublabel ?? null,
    seatsAvailable: partial.seatsAvailable ?? null,
    buildingShort: partial.buildingShort ?? null,
    subject: partial.subject ?? "",
    courseNumber: partial.courseNumber ?? "",
    sectionScheduleTypeKey: partial.sectionScheduleTypeKey ?? "lecture",
    meetingScheduleType: partial.meetingScheduleType ?? null,
    likelyExam: partial.likelyExam ?? false,
    likelyExamLabel: partial.likelyExamLabel ?? null,
    likelyExamInferenceSource: partial.likelyExamInferenceSource ?? null,
    ...partial,
  };
}

/** Static week used by the landing planner preview (SSR-friendly). */
export const LANDING_PREVIEW_BLOCKS: CalendarBlock[] = [
  block({
    key: "math-mon",
    plannerItemId: 1,
    sectionCrn: "10001",
    meetingId: 1,
    dayIndex: 0,
    startMinutes: 9 * 60,
    endMinutes: 10 * 60,
    label: "MATH 2200",
    color: COLOR_MATH,
    subject: "MATH",
    courseNumber: "2200",
    sublabel: "ENG 145",
    instructorSublabel: "Nguyen, T.",
    seatsAvailable: 12,
    buildingShort: "Engineering Building",
  }),
  block({
    key: "math-wed",
    plannerItemId: 1,
    sectionCrn: "10001",
    meetingId: 2,
    dayIndex: 2,
    startMinutes: 9 * 60,
    endMinutes: 10 * 60,
    label: "MATH 2200",
    color: COLOR_MATH,
    subject: "MATH",
    courseNumber: "2200",
    sublabel: "ENG 145",
    instructorSublabel: "Nguyen, T.",
    seatsAvailable: 12,
    buildingShort: "Engineering Building",
  }),
  block({
    key: "math-fri",
    plannerItemId: 1,
    sectionCrn: "10001",
    meetingId: 3,
    dayIndex: 4,
    startMinutes: 9 * 60,
    endMinutes: 10 * 60,
    label: "MATH 2200",
    color: COLOR_MATH,
    subject: "MATH",
    courseNumber: "2200",
    sublabel: "ENG 145",
    instructorSublabel: "Nguyen, T.",
    seatsAvailable: 12,
    buildingShort: "Engineering Building",
  }),
  block({
    key: "engl-tue",
    plannerItemId: 2,
    sectionCrn: "20002",
    meetingId: 4,
    dayIndex: 1,
    startMinutes: 11 * 60,
    endMinutes: 12 * 60 + 15,
    label: "ENGL 1010",
    color: COLOR_ENGL,
    subject: "ENGL",
    courseNumber: "1010",
    sublabel: "CR 302",
    instructorSublabel: "Rivera, M.",
    seatsAvailable: 4,
    buildingShort: "Classroom Building",
  }),
  block({
    key: "engl-thu",
    plannerItemId: 2,
    sectionCrn: "20002",
    meetingId: 5,
    dayIndex: 3,
    startMinutes: 11 * 60,
    endMinutes: 12 * 60 + 15,
    label: "ENGL 1010",
    color: COLOR_ENGL,
    subject: "ENGL",
    courseNumber: "1010",
    sublabel: "CR 302",
    instructorSublabel: "Rivera, M.",
    seatsAvailable: 4,
    buildingShort: "Classroom Building",
  }),
  block({
    key: "cosc-disc-tue",
    plannerItemId: 3,
    sectionCrn: "30003",
    meetingId: 6,
    dayIndex: 1,
    startMinutes: 12 * 60 + 20,
    endMinutes: 13 * 60 + 5,
    label: "COSC 2030",
    color: COLOR_COSC,
    subject: "COSC",
    courseNumber: "2030",
    sectionScheduleTypeKey: "discussion",
    meetingScheduleType: "Discussion",
    sublabel: "ENG 203",
    instructorSublabel: "Patel, A.",
    seatsAvailable: 18,
    buildingShort: "Engineering Building",
  }),
  block({
    key: "cosc-mon",
    plannerItemId: 3,
    sectionCrn: "30003",
    meetingId: 7,
    dayIndex: 0,
    startMinutes: 14 * 60,
    endMinutes: 15 * 60 + 15,
    label: "COSC 2030",
    color: COLOR_COSC,
    subject: "COSC",
    courseNumber: "2030",
    sublabel: "ENG 203",
    instructorSublabel: "Patel, A.",
    seatsAvailable: 18,
    buildingShort: "Engineering Building",
  }),
  block({
    key: "cosc-wed",
    plannerItemId: 3,
    sectionCrn: "30003",
    meetingId: 8,
    dayIndex: 2,
    startMinutes: 14 * 60,
    endMinutes: 15 * 60 + 15,
    label: "COSC 2030",
    color: COLOR_COSC,
    subject: "COSC",
    courseNumber: "2030",
    sublabel: "ENG 203",
    instructorSublabel: "Patel, A.",
    seatsAvailable: 18,
    buildingShort: "Engineering Building",
  }),
  block({
    key: "cosc-lab-thu",
    plannerItemId: 3,
    sectionCrn: "30003",
    meetingId: 9,
    dayIndex: 3,
    startMinutes: 15 * 60,
    endMinutes: 16 * 60,
    label: "COSC 2030 lab",
    color: COLOR_COSC,
    subject: "COSC",
    courseNumber: "2030",
    sectionScheduleTypeKey: "lab",
    meetingScheduleType: "Lab",
    sublabel: "HS 110",
    instructorSublabel: "Patel, A.",
    seatsAvailable: 18,
    buildingShort: "Health Sciences",
  }),
];
